apiVersion: projectcalico.org/v3
items:
- apiVersion: projectcalico.org/v3
  kind: IPPool
  metadata:
    name: default-ipv4-ippool
  spec:
    blockSize: 26
    cidr: 10.1.0.0/24
    ipipMode: Never
    natOutgoing: true
    nodeSelector: all()
    vxlanMode: Always
kind: IPPoolList
---
apiVersion: projectcalico.org/v3
items:
- apiVersion: projectcalico.org/v3
  kind: IPPool
  metadata:
    name: fixed-ipv4-ippool
  spec:
    blockSize: 26
    cidr: 10.1.1.0/24
    ipipMode: Never
    natOutgoing: false
    nodeSelector: "!all()"
    vxlanMode: Always
kind: IPPoolList