apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgC26scmxWH6B+JwgseB74Qt/vvLR93nmUR6OxwOOZRnelHYT/MnCDg1T3p9Ww45Cm/sMuDUvlF/d6tMo3rCTwL9xFxOQZCyQ+TjHwPYBKwkkv7iJX3UfB1SC8mrG2kMx64PO/hzK6K9jmT5rtlDhrhr0a0aYQ6sSN+gNBk6g47dS8KJ+RrCukmBuGbUPhi8xHX19bxl3uiivsUO4vEhFRTT2xqsHPPTF2MkxOth6nkKLknIO6sENCo6ZeSS33AkJAG5eYGDSUge8a1HpKMFHT3loKiqLlKjH1/seNjxwJ4zmrGEIOfve5+wjM52KWcK0+Ysw0qvSwUmY/mFNiKSeFkir5gXQQCC5DgP/ar8DNkWdYlXFkp2deXqlJSQ2Igmbzx6sfWhjVwu+VRFz0Bk5urU6HM5G74cGoBP3k1nApWl1sc2bTzPV4euveofQZv/4Sz72yqx3lQy1QI4udh+/sVZ0GDna4xMMdFhibM1JFnEZLCZO5dFE1tQXdvSG7EYNSYYKM0uNlueNkyyLxs6pQdMY/8cf8Qiy4LCoe9Q6F2exD6TQ2/EI0IaxUP8ruemXnAeKSICvRN5QRMKFBz96mdO8553ectbh7WdGEDAAvaosrXAvqcib0FLRbydZDZ6PObugThy1mXoNTpTUndemXuSU7Drb5rTwvIQUNHjwzvGHMSg1MmOLb+lfOfGnHiWNirqmrXUR7zTcbdYqPL1ZIBjI9lINo852rLI5CGwLEQXAw+eav1JmB8S
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager

