---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: bazarr
 labels:
   app: bazarr
 annotations:
   keel.sh/policy: force
   keel.sh/trigger: poll
   keel.sh/approvals: "1"
   keel.sh/pollSchedule: "@hourly"
spec:
 replicas: 1
 selector:
    matchLabels:
      app: bazarr
 template:
   metadata:
     labels:
       app: bazarr
   spec:
    containers:
       - name: bazarr
         image: linuxserver/bazarr:latest
         imagePullPolicy: Always
         ports:
           - containerPort: 6767
         volumeMounts:
           - mountPath: /config
             name: config
             subPath: bazarr
           - mountPath: /tv
             name: media
             subPath: Video/Series
           - mountPath: /movies
             name: media
             subPath: Video/Movies
         env:
         - name: PUID
           value: "0"
         - name: PGID
           value: "0"
         - name: TZ
           value: "Europe/Zurich"
    volumes:
      - name: config
        persistentVolumeClaim:
          claimName: local-conf-pvc
      - name: media
        persistentVolumeClaim:
          claimName: nas-media-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: bazarr-service
spec:
  selector:
    app: bazarr
  ports:
  - protocol: TCP
    port: 6767
    targetPort: 6767
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bazarr-ingress
spec:
  rules:
  - host: bazarr.int.sambaum.ch
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: bazarr-service
            port:
              number: 6767
