---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: crashplan
   labels:
     app: crashplan
 spec:
   replicas: 1
   selector:
      matchLabels:
        app: crashplan
   template:
     metadata:
       labels:
         app: crashplan
     spec:
      containers:
         - name: crashplan
           image: jlesage/crashplan-pro:v2.15.1
           ports:
             - containerPort: 5800
           volumeMounts:
             - mountPath: /config
               name: config
               subPath: crashplan
           env:
           - name: TZ
             value: "Europe/Zurich"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: local-conf-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: crashplan-service
spec:
  selector:
    app: crashplan
  ports:
  - protocol: TCP
    port: 5800
    targetPort: 5800
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crashplan-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
  - hosts:
    - "crashplan.int.sambaum.ch"
    secretName: crashplan-tls
  rules:
  - host: crashplan.int.sambaum.ch
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: crashplan-service
            port:
              number: 5800
