---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: jellyfin
 labels:
   app: jellyfin
 annotations:
   keel.sh/policy: "glob:version-*"
   keel.sh/trigger: poll
   keel.sh/approvals: "1"
   keel.sh/pollSchedule: "@hourly"
spec:
 replicas: 1
 selector:
    matchLabels:
      app: jellyfin
 template:
   metadata:
     labels:
       app: jellyfin
   spec:
    containers:
       - name: jellyfin
         image: linuxserver/jellyfin:version-10.7.7-1
         imagePullPolicy: Always
         ports:
           - containerPort: 8096
         volumeMounts:
           - mountPath: /config
             name: config
             subPath: jellyfin
           - mountPath: /data/movies
             name: media
             subPath: Video/Movies
           - mountPath: /data/tvshows
             name: media
             subPath: Video/Series
           - mountPath: /data/home-videos
             name: media
             subPath: Video/Home-Movies
           - mountPath: /data/home-photos
             name: nas-sam
             subPath: Personal/Fotos/Publish
         env:
         - name: PUID
           value: "0"
         - name: PGID
           value: "0"
         - name: TZ
           value: "Europe/Zurich"
    volumes:
      - name: config
        persistentVolumeClaim:
          claimName: local-conf-pvc
      - name: media
        persistentVolumeClaim:
          claimName: nas-media-pvc
      - name: nas-sam
        persistentVolumeClaim:
          claimName: nas-sam-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: jellyfin-service
spec:
  selector:
    app: jellyfin
  ports:
  - protocol: TCP
    port: 8096
    targetPort: 8096
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
  - hosts:
    - "jellyfin.int.sambaum.ch"
    - "jellyfin.sambaum.ch"
    secretName: jellyfin-tls
  rules:
  - host: jellyfin.int.sambaum.ch
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: jellyfin-service
            port:
              number: 8096
  - host: jellyfin.sambaum.ch
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: jellyfin-service
            port:
              number: 8096
