---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: keel
 labels:
   app: keel
 annotations:
   keel.sh/policy: force
   keel.sh/trigger: poll
   keel.sh/approvals: "1"
   keel.sh/pollSchedule: "@hourly"
spec:
 replicas: 1
 selector:
    matchLabels:
      app: keel
 template:
   metadata:
     labels:
       app: keel
   spec:
    containers:
       - name: keel
         image: keelhq/keel:latest
         imagePullPolicy: Always
         ports:
           - containerPort: 9300
         env:
          - name: BASIC_AUTH_USER
            value: admin
          - name: BASIC_AUTH_PASSWORD
            value: admin
          - name: WEBHOOK_ENDPOINT
            value: "http://keel-telegram-bot.int.sambaum.ch/"
---
kind: Service
apiVersion: v1
metadata:
  name: keel-service
spec:
  selector:
    app: keel
  ports:
  - protocol: TCP
    port: 9300
    targetPort: 9300
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keel-ingress
spec:
  rules:
  - host: keel.int.sambaum.ch
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: keel-service
            port:
              number: 9300
