---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: paperless
 labels:
   app: paperless
 annotations:
   keel.sh/policy: major
   keel.sh/trigger: poll
   keel.sh/approvals: "1"
   keel.sh/pollSchedule: "@hourly"
spec:
 replicas: 1
 selector:
    matchLabels:
      app: paperless
 template:
   metadata:
     labels:
       app: paperless
   spec:
    containers:
       - name: paperless
         image: linuxserver/paperless-ng:1.5.0
         imagePullPolicy: Always
         ports:
           - containerPort: 8000
         volumeMounts:
           - mountPath: /config
             name: config
             subPath: paperless
           - mountPath: /data
             name: data
             subPath: paperless
           - mountPath: /consume
             name: nas-sam
             subPath: Paperless-Consume
           - mountPath: /media
             name: nas-sam
             subPath: Paperless
         env:
         - name: PUID
           value: "0"
         - name: PGID
           value: "0"
         - name: TZ
           value: "Europe/Zurich"
         - name: PAPERLESS_CONSUMPTION_DIR
           value: "/consume"
         - name: PAPERLESS_CONSUMER_POLLING
           value: "3"
         - name: PAPERLESS_AUTO_LOGIN_USERNAME
           value: "sam"
         - name: DOCKER_MODS
           value: "linuxserver/mods:papermerge-multilangocr"
         - name: OCRLANG
           value: "deu,eng"
         - name: PAPERLESS_OCR_LANGUAGE
           value: "deu+eng"
         - name: PAPERLESS_FILENAME_FORMAT
           value: "{document_type}/{created_year}/{correspondent}-{created}-{tag_list}-{title}-ASN{asn}"
         - name: PAPERLESS_MEDIA_ROOT
           value: "/media"
         - name: PAPERLESS_WEBSERVER_WORKERS
           value: "4"
         - name: PAPERLESS_IGNORE_DATES
           value: "02.08.1985,16.12.1979,09.12.2016,19.03.2020"
         - name: PAPERLESS_CONSUMER_RECURSIVE
           value: "true"
    volumes:
      - name: config
        persistentVolumeClaim:
          claimName: local-conf-pvc
      - name: data
        persistentVolumeClaim:
          claimName: local-data-pvc
      - name: nas-temp
        persistentVolumeClaim:
          claimName: nas-temp-pvc
      - name: nas-sam
        persistentVolumeClaim:
          claimName: nas-sam-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: paperless-service
spec:
  selector:
    app: paperless
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paperless-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Frame-Options: allow";
spec:
  tls:
  - hosts:
    - "paperless.int.sambaum.ch"
    secretName: paperless-tls
  rules:
  - host: paperless.int.sambaum.ch
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: paperless-service
            port:
              number: 8000
