---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: radarr
 labels:
   app: radarr
 annotations:
   keel.sh/policy: minor
   keel.sh/trigger: poll
   keel.sh/approvals: "1"
   keel.sh/pollSchedule: "@hourly"
spec:
 replicas: 1
 selector:
    matchLabels:
      app: radarr
 template:
   metadata:
     labels:
       app: radarr
   spec:
    containers:
       - name: radarr
         image: linuxserver/radarr:4.0.5
         imagePullPolicy: Always
         ports:
           - containerPort: 7878
         volumeMounts:
           - mountPath: /config
             name: config
             subPath: radarr
           - mountPath: /downloads
             name: media
             subPath: Downloads
           - mountPath: /movies
             name: media
             subPath: Video/Movies
         env:
         - name: PUID
           value: "0"
         - name: PGID
           value: "0"
         - name: TZ
           value: "Europe/Zurich"
    volumes:
      - name: config
        persistentVolumeClaim:
          claimName: local-conf-pvc
      - name: media
        persistentVolumeClaim:
          claimName: nas-media-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: radarr-service
spec:
  selector:
    app: radarr
  ports:
  - protocol: TCP
    port: 7878
    targetPort: 7878
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
  - hosts:
    - "radarr.int.sambaum.ch"
    secretName: radarr-tls
  rules:
  - host: radarr.int.sambaum.ch
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: radarr-service
            port:
              number: 7878
