---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: sabnzbd
 labels:
   app: sabnzbd
 annotations:
   keel.sh/policy: major
   keel.sh/trigger: poll
   keel.sh/approvals: "1"
   keel.sh/pollSchedule: "@hourly"
spec:
 replicas: 1
 selector:
    matchLabels:
      app: sabnzbd
 template:
   metadata:
     labels:
       app: sabnzbd
   spec:
    containers:
       - name: sabnzbd
         image: linuxserver/sabnzbd:3.5.1
         imagePullPolicy: Always
         ports:
           - containerPort: 6789
         volumeMounts:
           - mountPath: /config
             name: config
             subPath: sabnzbd
           - mountPath: /downloads
             name: sabnzbd-downloads
             subPath: Downloads
           - mountPath: /incomplete-downloads
             name: sabnzbd-incomplete
             subPath: sabnzbd/incomplete-downloads
         env:
         - name: PUID
           value: "0"
         - name: PGID
           value: "0"
         - name: TZ
           value: "Europe/Zurich"
    volumes:
      - name: config
        persistentVolumeClaim:
          claimName: local-conf-pvc
      - name: sabnzbd-incomplete
        persistentVolumeClaim:
          claimName: local-data-pvc
      - name: sabnzbd-downloads
        persistentVolumeClaim:
          claimName: nas-media-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: sabnzbd-service
spec:
  selector:
    app: sabnzbd
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sabnzbd-ingress
  annotations:
    nginx.ingress.kubernetes.io/client-max-body-size: 100m
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
spec:
  rules:
  - host: sabnzbd.int.sambaum.ch
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: sabnzbd-service
            port:
              number: 8080
