---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: syslog-ng
 labels:
   app: syslog-ng
 annotations:
   keel.sh/policy: major
   keel.sh/trigger: poll
   keel.sh/approvals: "1"
   keel.sh/pollSchedule: "@hourly"
spec:
 replicas: 1
 selector:
    matchLabels:
      app: syslog-ng
 template:
   metadata:
     labels:
       app: syslog-ng
   spec:
    containers:
       - name: syslog-ng
         image: linuxserver/syslog-ng:3.30.1
         imagePullPolicy: Always
         # ports:
         #   - containerPort: 6601
         volumeMounts:
           - mountPath: /config
             name: config
             subPath: syslog-ng
           - mountPath: /var/log
             name: data
             subPath: syslog-ng
         env:
         - name: PUID
           value: "0"
         - name: PGID
           value: "0"
         - name: TZ
           value: "Europe/Zurich"
    volumes:
      - name: config
        persistentVolumeClaim:
          claimName: local-conf-pvc
      - name: data
        persistentVolumeClaim:
          claimName: local-data-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: syslog-ng-service
  annotations:
    metallb.universe.tf/allow-shared-ip: "hare-192.168.1.26"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.26
  selector:
    app: syslog-ng
  ports:
  - protocol: TCP
    port: 601
    targetPort: 601
    name: syslog-ng-tcp
---
kind: Service
apiVersion: v1
metadata:
  name: syslog-ng-service-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: "hare-192.168.1.26"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.26
  selector:
    app: syslog-ng
  ports:
  - protocol: UDP
    port: 514
    targetPort: 514
    name: syslog-ng-udp





