loki:
  enabled: true
  persistence:
    enabled: true
    storageClassName: openebs-local-hostpath-data
    accessModes:
      - ReadWriteOnce
    size: 1Gi

# loki:
#   enabled: true
#   persistence:
#     enable: true
#     # storageClassName: openebs-local-hostpath-data
#     size: 1Gi

# --set loki.persistence.enabled=true,loki.persistence.storageClassName=openebs-local-hostpath-data,loki.persistence.size=1Gi

promtail:
  enabled: true
  # extraScrapeConfigs: |
  #   - job_name: syslog
  #     syslog:
  #       listen_address: 0.0.0.0:1514
  #       labels:
  #         job: "syslog"
  #     relabel_configs:
  #       - source_labels: ['__syslog_message_hostname']
  #         target_label: 'host'
  syslogService:
    enabled: true
    type: LoadBalancer
    port: 1514
  extraScrapeConfigs:
    - job_name: syslog
      syslog:
        listen_address: 0.0.0.0:1514
        idle_timeout: 60s
        label_structured_data: yes
        labels:
          job: "syslog"
      relabel_configs:
        - source_labels: ['__syslog_message_hostname']
          target_label: 'host'

grafana:
  enabled: false
  sidecar:
    datasources:
      enabled: true
  image:
    tag: 8.1.6
