# https://github.com/k8s-at-home/library-charts/blob/main/charts/stable/common/values.yaml

env:
  name: TIMEZONE
  value: "Europe/Zurich"

persistence:
  config:
    enabled: true
    type: pvc
    # mountPath: /opt/recipes
    readOnly: false
    # nameOverride:
    storageClass: openebs-local-hostpath-conf
    # existingClaim: openebs-local-hostpath-conf-pvc
    # subPath: recipes # some-subpath
    accessMode: ReadWriteOnce
    size: 1Gi
    retain: true
  media:
    enabled: true
    type: pvc
    mountPath: /opt/recipes/mediafiles
    readOnly: false
    # nameOverride:
    storageClass: openebs-local-hostpath-conf
    # existingClaim: openebs-local-hostpath-conf-pvc
    # subPath: recipes # some-subpath
    accessMode: ReadWriteOnce
    size: 1Gi
    retain: true
  # db:
  #   enabled: true
  #   type: pvc
  #   mountPath: /var/lib/postgresql/data
  #   readOnly: false
  #   # nameOverride:
  #   storageClass: openebs-local-hostpath-conf
  #   # existingClaim: openebs-local-hostpath-conf-pvc
  #   # subPath: recipes # some-subpath
  #   accessMode: ReadWriteOnce
  #   size: 1Gi
  #   retain: true
  static:
    enabled: true
    type: emptyDir
    mountPath: /opt/recipes/staticfiles
