apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-nfs
spec:
  capacity:
    storage: 10Gi
  storageClassName: standard
  accessModes:
  - ReadWriteMany
  nfs:
    server: nas.int.sambaum.ch
    path: "/volume1/Kubernetes"
